---
name: Upload coverage reports to Codecov
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '16.0'
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          node-version: '16.0'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
      - name: Run tests with coverage
        run: pytest --cov=.
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
